### ISSUE TITLE
ROS Sync

### ISSUE THREAD

**Issue by lukicdarkoo** [pantor/ruckig#101]
First of all, thanks for the great tool!

I was wondering whether we can get ROS sync (at least for Foxy)?

```
$ sudo apt show ros-foxy-ruckig
Package: ros-foxy-ruckig
Version: 0.4.0-1focal.20210901.032321
Priority: optional
Section: misc
Maintainer: Lars Berscheid <lars.berscheid@kit.edu>
Installed-Size: 288 kB
Depends: libc6 (>= 2.29), libstdc++6 (>= 4.1.1), ros-foxy-ros-workspace
Download-Size: 77.4 kB
APT-Manual-Installed: yes
APT-Sources: http://packages.ros.org/ros2-testing/ubuntu focal/main amd64 Packages
Description: Online Trajectory Generation.
 Real-time. Jerk-constrained. Time-optimal.
```

The current Ruckig version is 0.6.2 while the Ruckig ROS version is 0.4.0.

**Comment by pantor** [comment]
I've now opened the corresponding PRs at [rosdistro](https://github.com/ros/rosdistro/pulls). It may take a few days until they are synced with rosindex.

Unfortunately, adding this step [to the CI/CD](https://github.com/pantor/ruckig/blob/master/.github/workflows/publish-ros.yml) did not work out - if you have any ideas why, please let me know.
