### ISSUE TITLE
Flaky oscillations when Ruckig timestep is not constant

### ISSUE THREAD

**Issue by AndyZe** [pantor/ruckig#104]
With a constant timestep, we get nice behavior out of Ruckig. But if the input has a different timestep at every iteration, we occasionally see oscillations. Got any insight on this?

Constant timestep on the left, dynamic timestep on the right:
![ruckig_dynamic_timestep](https://user-images.githubusercontent.com/11284393/155024839-4ef96460-b0aa-48e3-841c-7d05f91bb4b3.png)

Zoomed on the unexpected oscillation:
![zoomed](https://user-images.githubusercontent.com/11284393/155024886-01737192-548c-4515-9cfe-2c04fc1724fa.png)

Here's the code used for the dynamic timesteps. It just constructs a new Ruckig instance with a different timestep at every waypoint:

```
      timestep = trajectory.getWayPointDurationFromPrevious(waypoint_idx + 1);
      ruckig_ptr = std::make_unique<ruckig::Ruckig<RUCKIG_DYNAMIC_DOF>>(num_dof, timestep);
```

**Comment by AndyZe** [comment]
For the nice constant timestep graph, the timestep was 0.1s. For the wacky dynamic timestep graph, it ranged from 0.03-0.25s.

**Comment by pantor** [comment]
Hey @AndyZe! Can you provide me a bit more information here, maybe even a simple code example? Are the figures showing the position over time? Ruckig is not really meant to be used with dynamic time steps, so I'm not exactly sure what's going on here.

**Comment by pantor** [comment]
Feel free to reopen, but I think I need more information to help here.
