### ISSUE TITLE
Python Library compilation error on jetson Nano

### ISSUE THREAD

**Issue by Ruslan2288** [pantor/ruckig#105]
when executing commands:

git clone https://github.com/pantor/ruckig 
cd ruckig
git clone https://github.com/pybind/pybind11.git
pip install .

the following error occurs:

![image](https://user-images.githubusercontent.com/40971329/155277328-7ede17e9-90e4-4c2a-bbdb-6d8ba5ff90b1.png)

**Comment by pantor** [comment]
This should be fixed with the latest commit. Thanks for pointing it out!
