### ISSUE TITLE
Can I use the method of intermediate waypoints offline ?

### ISSUE THREAD

**Issue by WangXingfang** [pantor/ruckig#112]
Can I use the method of intermediate waypoints offline ?

**Comment by pantor** [comment]
Sure! This feature is available in [Ruckig Pro](https://ruckig.com), which is a commercial product that makes this open-source version here possible. If you are interested, feel free to shoot me a mail at *info@ruckig.com*.

**Comment by ybbng** [comment]
I would like to use the commercial version([Ruckig Pro]) and have sent an email, but I haven't received a response yet. Could you please let me know what the issue might be?
