### ISSUE TITLE
trajectory not calculated

### ISSUE THREAD

**Issue by old-ma** [pantor/ruckig#115]
Hi,
In ruckig::Ruckig::update(), the trigger of updating trajectory depends on if (input!=current_input).
Somtimes,  at the first time runing update(), even the current_input is not assigned by input but the value of current_input has already been equal to input, Especially the object of class Ruckig is created repeatly in for loop, the compiler gives the some memory address to ruckig, so that the current_input has the same value of last one. In this case, if the same input is gived, the trajectory will not be created, so the result will be wrong.

**Comment by pantor** [comment]
This should be fixed with the latest commit. Thanks for reporting!
