### ISSUE TITLE
The best way to extract the jerk profile and duration of each segment?

### ISSUE THREAD

**Issue by Aymenzerahmed** [pantor/ruckig#117]
Hi,
I wish to know the best way to extract the jerk profile from the ruckig trajectory?

**Comment by pantor** [comment]
Hi, in the C++ version the `profiles` member in the `Trajectory` class contain all the relevant information. They are a list of `Profile`, which contain the `t` and `j` arrays with the switching times and the jerk values. In the Python version, you would need to build it by yourself with the `ÈXPOSE_INTERNAL` CMake flag enabled. Then, the mentioned classes and members are wrapped and can be used in Python similarly.
