### ISSUE TITLE
Reorder your initialization lists

### ISSUE THREAD

**Issue by mangoschorle** [pantor/ruckig#133]
Compilers in strict mode and Werror will fail on initialization lists as (taken from ruckig.hpp)

`    explicit Ruckig(double delta_time): degrees_of_freedom(DOFs), delta_time(delta_time), max_number_of_waypoints(0) {
`    

This is due to Wreorder, i.e. you should reorder the initialization lists to match the order in the header.

**Comment by pantor** [comment]
All warnings (`Wall`) by gcc and clang should be fixed and are now checked by the CI.
