### ISSUE TITLE
[Compile Error]: ‘af_scale’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

### ISSUE THREAD

**Issue by MingshanHe** [pantor/ruckig#135]
Dear,

I have a compile error during `make` process.

The terminal information has been followed as:
![image](https://user-images.githubusercontent.com/56861752/178186727-cfda66b1-1138-4af7-a1ed-8af98a75a506.png)

I have tried to delete the `af_scale` variable and the project has been compiled successfully.
But this variable is the same as the others, like `v0_scale`, `a0_scale`, `vf_scale`. So I open this issue to get your help.

Best regards,
Mingshan

**Comment by pantor** [comment]
This is a compiler warnings that is treated as an error due to the used `-Werror` compiler flag. The recent commit on the master branch removes that flag, so you should be able to compile Ruckig without error now. I'll keep that issue open until I fix the underlying warning. Thanks!

**Comment by pantor** [comment]
The warning is now fixed on master.
