### ISSUE TITLE
using Ruckig Pro

### ISSUE THREAD

**Issue by yzy244001743** [pantor/ruckig#143]
Hi:   
I want  to download Ruckig Pro ，to deal with Waypoint-based Trajectory Generation real-time, the  online API is too time-consuming.
But it need to  register an account. What do I need to do? Is there any charge for this?

**Comment by pantor** [comment]
Hi @yzy244001743, thanks for your interest! Correct, there is a charge to download Ruckig Pro and use the waypoint-based trajectory generation on your local machine. If you have commercial interest, we are happy to [talk](mailto:info@ruckig.com) about your use case and proceed with a free trial version for a limited period of time.
