### ISSUE TITLE
How are derivatives calculated?

### ISSUE THREAD

**Issue by AndyZe** [pantor/ruckig#155]
I'm mostly just curious how derivatives are calculated. Is it backward finite difference, central finite difference, or something else?

**Comment by pantor** [comment]
Which derivatives are you referring to?

**Comment by AndyZe** [comment]
I'm not sure, I just assumed you were calculating vel/accel/jerk from position, somewhere

**Comment by pantor** [comment]
We don't calculate derivatives explicitly during run-time (in the Community version). In general, all equations are calculated analytically beforehand.
