### ISSUE TITLE
Time arbitrarily Ruckig? 

### ISSUE THREAD

**Issue by sinamr-sony** [pantor/ruckig#157]
Ruckig always provides the time-optimal trajectory, but as it was mentioned in the paper, the provided library is capable to synchronize multiple trajectories (for multi-DOF systems) such that all the joints reach their target at the same time. So, theoretically, it should be possible to modify it such that it generate trajectory for an arbitrarily target time  (which should be clearly longer that the optimal time trajectory). I tried to understand the code and modify it accordingly but I failed to do; has anyone else had thought about this?

**Comment by pantor** [comment]
This can be done via the `minimum_duration` parameter of the `InputParameter` class.
