### ISSUE TITLE
Showcase for ruckig

### ISSUE THREAD

**Issue by martburg** [pantor/ruckig#158]
Not really an issue but something to play with:
 
https://github.com/wiredworks/ruckig-showcase

a simple Showcase using kivy can be found

with kind regards Martin

**Comment by pantor** [comment]
That's great, thanks for letting me know!

I'd also gladly add wiredworks to the list of users at the end of the Readme, in case that's alright with you.

**Comment by martburg** [comment]
Go ahead ;-))
