### ISSUE TITLE
./example-3_waypoints  Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by dbdxnuliba** [pantor/ruckig#161]
version:0.9.2
dell@dell:~/ws_ruckig/build/ruckig$ ./example-3_waypoints 
t | p1 | p2 | p3
[ruckig] calculate trajectory via online API server.
Segmentation fault (core dumped)

**Comment by pantor** [comment]
Thanks for spotting this. It seems that this segmentation fault is thrown if no internet connection is available while trying to reach our API server.

I've now added a check for this in the recent commit on the master branch. Can you try again with this one?

**Comment by dbdxnuliba** [comment]
is the remote api not opensourced

**Comment by pantor** [comment]
The algorithm for intermediate waypoints is not open source, but is part of the (commercial) Ruckig Pro version that also keeps this open source project going.

Just to be precise, the interface itself is open source and available [here](http://api.ruckig.com/docs).

**Comment by dbdxnuliba** [comment]
ok ，how much the  (commercial) Ruckig Pro version

**Comment by pantor** [comment]
Thanks for your interest! Please send us a quick mail at [info@ruckig.com](mailto:info@ruckig.com), and we will get back to you there.

**Comment by dbdxnuliba** [comment]
ok ，thanks
