### ISSUE TITLE
Optional header not found

### ISSUE THREAD

**Issue by heshengdang** [pantor/ruckig#168]
hello,    I reported an error while executing the 'make' step：  In file included from /home/he/ruckig/src/position-step1.cpp:1:0:
/home/he/ruckig/include/ruckig/ruckig.hpp:10:20: fatal error: optional: 没有那个文件或目录

**Comment by pantor** [comment]
Ruckig is written in C++17, which introduced `optional`. Which compiler version are you using?

If you still need to use C++11, you can apply a small patch by executing `bash scripts/patch-c++11.sh`. More info in the Readme.
