### ISSUE TITLE
Velocity/acceleration/jerk constraints for entire motion (not per DOF)

### ISSUE THREAD

**Issue by marcel13p** [pantor/ruckig#196]
Dear pantor,

I am using ruckig for a project with a delta robot. Ruckig works great for planning the trajectory. However, I do not wish to set velocity, acceleration or jerk constraints for x, y, and z independently, but for the whole motion. I would like to set a v_max_global so that v_max_global = sqrt(v_x_max^2+v_y_max^2+v_z_max^2). Now I need to first calculate the direction of the movement, normalize it and multiply it by my constraints to get the correct maximum constraint for the combined motion. This method feels quite hacky and I imagine it only works for phase synchronization.

**Comment by pantor** [comment]
You're correct, Ruckig currently only supports constraints per axis. Adding more complex constraints would require knowledge about the kinematics of the system, and is therefore currently out of scope as we want Ruckig to remain a simple low-level trajectory generator. 

Your solution would work for phase synchronized motions. Another alternative would be to move slower with `v_max_global / sqrt(3)` for each axis.
