### ISSUE TITLE
Typo in Cmake example (undefined reference to ruckig::CloudClient)

### ISSUE THREAD

**Issue by JornJorn** [pantor/ruckig#198]
`examples/CMakeLists-installed.txt` contains the following line
`target_link_libraries(example-position PRIVATE ruckig::ruckig)`

However, this gives me an error about an undefined reference to ruckig::CloudClient. Changing the line to 
`target_link_libraries(example-position PRIVATE ruckig)`
solves the issue. 

I didn't create a PR, as I am unsure whether the example or the implementation is incorrect.

**Comment by pantor** [comment]
Hi @JornJorn - sorry for the late response. It seems that you have installed Ruckig system-wide, and that the shared library was compiled with the `BUILD_CLOUD_CLIENT =OFF` flag. By changing `ruckig::ruckig` to `ruckig`, you are now compiling the source files yourself that doesn't have this flag mismatch anymore. An alternative would be to disable the cloud client in your build - assuming you don't need it that feature.
