### ISSUE TITLE
The Mathematica notebook regarding step 2 is discrepant from the statement in the paper.

### ISSUE THREAD

**Issue by huangjiancong1** [pantor/ruckig#210]
Why the solutions in [ruckig-step2-uddu.nb](https://github.com/pantor/ruckig/blob/v0.5.0/notebooks/ruckig-step2-uddu.nb)

is different with the _E. Step 2: Time Synchronization_ in the paper?

Difference:
| Paper | Mathematica |
| :---: | :---: |
| changing the velocity plateau VEL to vplat | `a3=aPlate`, not use vplate|
| using `t5 = 0` | using `a3 = 0` |
| | |

Could you please explain why the implementation is different? Why is one being used in the latest C implementation?

**Comment by pantor** [comment]
Thanks for your interest. Without going into too many details, there are differences regarding computational performance and generality of the solutions.
