### ISSUE TITLE
RuntimeError: [ruckig] error in step 2 in dof: 0 for t sync: 1.403613 input

### ISSUE THREAD

**Issue by mynamedaike** [pantor/ruckig#24]
Hello, I encountered the following error when I used Ruckig to plan a trajectory. Can anyone help me with this problem?

RuntimeError: [ruckig] error in step 2 in dof: 0 for t sync: 1.403613 input: 
inp.current_position = [0.01073568005271233, -0.7002627264230739, 0.08182424814164639, -2.453889055015553, -0.08363270962592464, 1.829417851685384, 0.7163509366199623]
inp.current_velocity = [0.05656281587106524, 1.011281770884991, 0.9677565166950226, 0.9125879855751985, -0.9937611499130723, 0.9963710898160936, -0.8048512544333941]
inp.current_acceleration = [-5.348847133445708, -3.400994300842285, -3.708171844482422, -3.951635360717773, 3.508039474487305, -3.532837390899658, 4.73619270324707]
inp.target_position = [0.0698, 0.6283, 0.6981000000000001, -2.1642, -0.733, 2.5482, 0.5061]
inp.target_velocity = [0, 0, 0, 0, 0, 0, 0]
inp.target_acceleration = [0, 0, 0, 0, 0, 0, 0]
inp.max_velocity = [1, 1, 1, 1, 1, 1, 1]
inp.max_acceleration = [7, 7, 7, 7, 7, 7, 7]
inp.max_jerk = [1000, 1000, 1000, 1000, 1000, 1000, 1000]

Thanks in advance.

**Comment by pantor** [comment]
Hi @mynamedaike, this error should be fixed by the latest commit. Can you confirm?
