### ISSUE TITLE
Issue with cpp11 patch

### ISSUE THREAD

**Issue by Danielxyz123** [pantor/ruckig#35]
Visual Studio tells me that 

"[[maybe_unused]]" 
 for example in the following line

 inline bool check([[maybe_unused]] double tf, double jf, double vMax, double vMin, double aMax, double aMin) {

ist not available for cpp11. Or is it my fault?

**Comment by pantor** [comment]
All errors should be fixed now, at least using GCC version 5 on Ubuntu 18.04 (as this is tested now in CI). Can you confirm this?

**Comment by Danielxyz123** [comment]
Thx a lot. Yes it works in Visual Studio (Win), but only without compiler WX flag...

There are Error like:

Warnung	C4127	Bedingter Ausdruck ist konstant	

For Example in the following Line (line 56 in profile.hpp)

       if (limits == Limits::ACC0) {

**Comment by pantor** [comment]
Ok, I've now removed the flags for treating warnings as errors for the C++ patch. Unfortunately, I don't have the time to fix the warnings itself.

**Comment by Danielxyz123** [comment]
👍

**Comment by Danielxyz123** [comment]
Hi Pantor, i only want so give some feedback. It's working on the B&R PLC with the cpp11 patch! It uses the GCC Compiler 6.3.0. The performance seems to be good. Great work 👍
