### ISSUE TITLE
Wrong behaviour when changing max_velocity on the fly

### ISSUE THREAD

**Issue by mdhom** [pantor/ruckig#44]
Hi,

i was testing around with my python on the fly example (see open PR) and discovered the following behaviour:
![image](https://user-images.githubusercontent.com/30362954/124777227-58769700-df40-11eb-9a41-04e46a87671a.png)
What is happening: i start a trajectory with `target_position=10` and `max_velocity=3`. After position is greater than 0.7, i update the trajectory with new InputParameters, where `max_velocity=1`. I would expect, that velocity goes directly down to 1, but instead (as you can see in the trace) the velocity "overshoots" the new target_velocity and goes below 1! I do not understand why it behaves like this, i'd expect it to move along the path painted in red.

I can even create a situation where something totally strange happens, the velocity actually changes its sign for some time (movement direction is reversed), which i think should not happen at all:
![image](https://user-images.githubusercontent.com/30362954/124780562-fb301500-df42-11eb-99e0-172d39fa6eab.png)

Can you help me with what i'm doing wrong here?

You can find the example source for that output [here](https://pastebin.com/1gbQcmQg).

**Comment by pantor** [comment]
Hi @mdhom,

this is intendend behaviour: Ruckig will first and foremost try to get the kinematic state within the allowed limits as fast as possible. Only then a time-optimal trajectory is calculated. 

See #17 for a related discussion. I would like to have an option that disables this behaviour, however it would require a few more equations in step 1 of Ruckig.

**Comment by mdhom** [comment]
oh damn, that makes the library quite unusable for me. I am justing moving a car with the trajectory, Imagine how stupid it looks when the car moves backwards although it only needs to change velocity...
________________________________

**Comment by pantor** [comment]
That's unfortunate to hear. I've now opened issue #45.
