### ISSUE TITLE
Python position_extrema seg fault

### ISSUE THREAD

**Issue by ljarin** [pantor/ruckig#48]
Hello again,

I tried out the python binding for Trajectory.position_extrema, and was getting a seg fault. I believe this was caused by 0 being passed in for DOFs for the binding, causing the Vector to be size 0. I think I fixed it here https://github.com/ljarin/ruckig/commit/6bf9303a495719c301ef8cde0fc06652c41dfc80, but I didn't run your tests

**Comment by pantor** [comment]
Thanks for catching this one! The latest commit should fix this.
