### ISSUE TITLE
Target state is not reached exactly due to discrete cycle time

### ISSUE THREAD

**Issue by githublth** [pantor/ruckig#59]
hi, I have a question, input parameters as below:

![image](https://user-images.githubusercontent.com/25904480/127950875-355950c0-cf24-42a1-82bf-a4e87368295a.png)
and target_velocity and target_acceleration is not zero.  when reach the last cycle(time>duration) like described in the code
![image](https://user-images.githubusercontent.com/25904480/127951284-13d7e6ea-b874-4c6d-982a-fa212350953c.png)
parametre output as below:
![image](https://user-images.githubusercontent.com/25904480/127951581-834018e8-d009-4277-91da-88b036ef85ab.png)
only target_acceleration is correct. I don't know if I understand it correctly, let me know.
thanks!

**Comment by pantor** [comment]
The duration of the trajectory is not a multiple of your cycle time `0.001`. There is a remaining duration after the exact position, velocity and acceleration are reached. In this time, the robot continues its motions with constant acceleration, as the robot cannot suddenly stop while moving without violating its kinematic limits.

If you want to reach the target state at an exact multiple of your cycle time, you can set
```
input. duration_discretization = DurationDiscretization::Discrete;
```
