### ISSUE TITLE
Ruckig Pro version and intermediate waypoints

### ISSUE THREAD

**Issue by caomuqing** [pantor/ruckig#78]
Hi,

Thank you for this useful package. May I ask how to get the Pro version of the software? Also, is it possible to share the techniques used to generate intermediate states (vel, acc) for the given intermediate waypoints? Just some brief description will be helpful. Thank you!

Best Regards,
mq

**Comment by pantor** [comment]
Hi @caomuqing, please drop me a line at info@ruckig.com, I'll then answer your questions by email. Thanks for your interest!
