### ISSUE TITLE
I can't compile a library for python on raspberry pi

### ISSUE THREAD

**Issue by Ruslan2288** [pantor/ruckig#93]
![image](https://user-images.githubusercontent.com/40971329/144398620-3b974f7e-8a3f-4770-8a6a-e462cfd477f3.png)
![image](https://user-images.githubusercontent.com/40971329/144398729-b6b800bb-1109-48fd-bdef-7dc899ace9c4.png)

On raspberry pi, the library is not installed using pip when compiling, it writes the same error as in the photo.

**Comment by Ruslan2288** [comment]
Please tell me what I need to do to install it. I installed pybind11, but the compiler doesn't seem to see it

**Comment by pantor** [comment]
Alas there are no pre-build binaries for ARM, so it wants to compile the library including the Python wrapper. For that, it needs to find [pybind11](https://github.com/pybind/pybind11). You can either install that globally, or just clone it into the Ruckig directory. 
```
cd ruckig
git clone https://github.com/pybind/pybind11.git
```
CMake should pick Pybind11 up from there.
