### ISSUE TITLE
Error while building the source code for pro version 

### ISSUE THREAD

**Issue by robodreamer** [pantor/ruckig#99]
Hi I am trying out the latest pro version (0.6.0) for evaluation purposes. I got an error while building the code (see the attached screenshot below). Can you see what is causing it? It seems that WaypointsCalculator class cannot be found from the header files that were used in the example. 
![image](https://user-images.githubusercontent.com/5122307/147111081-8528519a-f91b-4f99-861d-fe0516769daf.png)

**Comment by pantor** [comment]
Hi @robodreamer!

The patch release v0.6.2 should fix this issue, and is available at [releases.ruckig.com](https://releases.ruckig.com). Alternatively, you can just disable the tests using the current version by setting the CMake variables `-DBUILD_TESTS=OFF`.
